[package]
name = "oasgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oasgen-core = { path = "../core" , package = "oasgen-core" }
oasgen-macro = { path = "../macro" , package = "oasgen-macro" }
openapiv3 = { git = "https://github.com/kurtbuilds/openapiv3" }