[package]
name = "oasgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.2.1", optional = true }
http = "0.2.8"
indexmap = "1.9.2"
oasgen-core = { path = "../core", package = "oasgen-core" }
oasgen-macro = { path = "../macro", package = "oasgen-macro" }
openapiv3 = { git = "https://github.com/kurtbuilds/openapiv3" }
serde = { version = "1.0.151", features = ["derive"] }

[features]
default = ["actix"]
actix = ["actix-web"]

[dev-dependencies]
trybuild = "1.0.73"
