[package]
name = "oasgen-core"
version = "0.1.7"
edition = "2021"
authors = ["Kurt Wolf <kurtwolfbuilds@gmail.com>"]
description = "Dependency of oasgen. Generates OpenAPI 3.0 spec based on Rust code. Works with actix-web, but architected to easily extend to other frameworks (or no framework)."
license = "MIT"
repository = "https://github.com/kurtbuilds/oasgen"
homepage = "https://github.com/kurtbuilds/oasgen"
documentation = "https://docs.rs/oasgen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.2.1", optional = true }
indexmap = "1.9.2"
openapiv3-extended = "1.0.13"
uuid = { optional = true, version = "1.2.2" }
chrono = { optional = true, version = "0.4.23" }
pin-project-lite = "0.2.9"

[features]
default = ["uuid", "chrono"]
actix = ["actix-web"]

[dev-dependencies]
assert_matches = "1.5.0"
