
[package]
name = "oasgen-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
indexmap = "1.9.2"
openapiv3 = { git = "https://github.com/kurtbuilds/openapiv3" }
uuid = { optional = true, version = "1.2.2" }


[features]
default = ["uuid"]

[dev-dependencies]
assert_matches = "1.5.0"
