openapi: 3.0.3
info:
  title: ''
  version: ''
paths:
  /auth/send-code:
    get:
      summary: custom custom read all about it
      operationId: send_code_transformed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCode'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendCodeResponse'
components:
  schemas:
    SendCode:
      type: object
      properties:
        mobile:
          type: string
    SendCodeResponse:
      type: object
      properties:
        found_account:
          type: boolean
